export const LIFE_EVENTS_FLAGS = {
    ENABLE_MODIFYING_LIFE_EVENTS: 'enableModifyingLifeEvents',
    ENABLE_FINANCIAL_GOALS: 'enableFinancialGoals',
};

export const LIFE_EVENTS_FLAGS_DEFAULTS = {
    [LIFE_EVENTS_FLAGS.ENABLE_MODIFYING_LIFE_EVENTS]: true,
    [LIFE_EVENTS_FLAGS.ENABLE_FINANCIAL_GOALS]: false,
};
