/**
 * @license Copyright (c) Microsoft Corporation. All rights reserved.
 */
import { SimpleFormatter } from "../../CustomControls/Models/PropertyFallbacks/Formatting/SimpleFormatters";
export var DefaultFormattingData = {
    timeZoneUtcOffsetMinutes: -480,
    dateTimeFormatInfo: {
        AMDesignator: "AM",
        AbbreviatedDayNames: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        AbbreviatedMonthGenitiveNames: [
            "Jan",
            "Feb",
            "Mar",
            "Apr",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Oct",
            "Nov",
            "Dec",
            "",
        ],
        AbbreviatedMonthNames: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", ""],
        CalendarWeekRule: 0,
        Calendar: {
            MinSupportedDateTime: new Date(),
            MaxSupportedDateTime: new Date(),
            AlgorithmType: 1,
            CalendarType: 1,
            Eras: [1],
            TwoDigitYearMax: 2029,
            IsReadOnly: false,
            minSupportedDateTime: new Date(),
            maxSupportedDateTime: new Date(),
            algorithmType: 1,
            calendarType: 1,
            eras: [1],
            twoDigitYearMax: 2029,
            isReadOnly: false,
        },
        DateSeparator: "/",
        DayNames: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        FirstDayOfWeek: 0,
        FullDateTimePattern: "dddd, MMMM d, yyyy h:mm:ss tt",
        LongDatePattern: "dddd, MMMM d, yyyy",
        LongTimePattern: "h:mm:ss tt",
        MonthDayPattern: "MMMM dd",
        MonthGenitiveNames: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
            "",
        ],
        MonthNames: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
            "",
        ],
        PMDesignator: "PM",
        ShortDatePattern: "M/d/yyyy",
        ShortTimePattern: "h:mm tt",
        ShortestDayNames: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
        SortableDateTimePattern: "yyyy'-'MM'-'dd'T'HH':'mm':'ss",
        TimeSeparator: ":",
        UniversalSortableDateTimePattern: "yyyy'-'MM'-'dd HH':'mm':'ss'Z'",
        YearMonthPattern: "MMMM yyyy",
        amDesignator: "AM",
        abbreviatedDayNames: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        abbreviatedMonthGenitiveNames: [
            "Jan",
            "Feb",
            "Mar",
            "Apr",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Oct",
            "Nov",
            "Dec",
            "",
        ],
        abbreviatedMonthNames: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", ""],
        calendarWeekRule: 0,
        calendar: {
            MinSupportedDateTime: new Date(),
            MaxSupportedDateTime: new Date(),
            AlgorithmType: 1,
            CalendarType: 1,
            Eras: [1],
            TwoDigitYearMax: 2029,
            IsReadOnly: false,
            minSupportedDateTime: new Date(),
            maxSupportedDateTime: new Date(),
            algorithmType: 1,
            calendarType: 1,
            eras: [1],
            twoDigitYearMax: 2029,
            isReadOnly: false,
        },
        dateSeparator: "/",
        dayNames: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        firstDayOfWeek: 0,
        fullDateTimePattern: "dddd, MMMM d, yyyy h:mm:ss tt",
        longDatePattern: "dddd, MMMM d, yyyy",
        longTimePattern: "h:mm:ss tt",
        monthDayPattern: "MMMM dd",
        monthGenitiveNames: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
            "",
        ],
        monthNames: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
            "",
        ],
        pmDesignator: "PM",
        shortDatePattern: "M/d/yyyy",
        shortTimePattern: "h:mm tt",
        shortestDayNames: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
        sortableDateTimePattern: "yyyy'-'MM'-'dd'T'HH':'mm':'ss",
        timeSeparator: ":",
        universalSortableDateTimePattern: "yyyy'-'MM'-'dd HH':'mm':'ss'Z'",
        yearMonthPattern: "MMMM yyyy",
    },
    numberFormatInfo: {
        CurrencyDecimalDigits: 2,
        CurrencyDecimalSeparator: ".",
        CurrencyGroupSeparator: ",",
        CurrencyGroupSizes: [3],
        CurrencyNegativePattern: 0,
        CurrencyPositivePattern: 0,
        CurrencySymbol: "$",
        NativeDigits: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
        NANSymbol: "",
        NegativeInfinitySymbol: "-Infinity",
        NegativeSign: "-",
        NumberDecimalDigits: 2,
        NumberDecimalSeparator: ".",
        NumberGroupSeparator: ",",
        NumberGroupSizes: [3],
        NumberNegativePattern: 1,
        PerMilleSymbol: "�",
        PercentDecimalDigits: 2,
        PercentDecimalSeparator: ".",
        PercentGroupSeparator: ",",
        PercentGroupSizes: [3],
        PercentNegativePattern: 0,
        PercentPositivePattern: 0,
        PercentSymbol: "%",
        PositiveInfinitySymbol: "Infinity",
        PositiveSign: "+",
        currencyDecimalDigits: 2,
        currencyDecimalSeparator: ".",
        currencyGroupSeparator: ",",
        currencyGroupSizes: [3],
        currencyNegativePattern: 0,
        currencyPositivePattern: 0,
        currencySymbol: "$",
        nativeDigits: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
        nanSymbol: "",
        negativeInfinitySymbol: "-Infinity",
        negativeSign: "-",
        numberDecimalDigits: 2,
        numberDecimalSeparator: ".",
        numberGroupSeparator: ",",
        numberGroupSizes: [3],
        numberNegativePattern: 1,
        perMilleSymbol: "�",
        percentDecimalDigits: 2,
        percentDecimalSeparator: ".",
        percentGroupSeparator: ",",
        percentGroupSizes: [3],
        percentNegativePattern: 0,
        percentPositivePattern: 0,
        percentSymbol: "%",
        positiveInfinitySymbol: "Infinity",
        positiveSign: "+",
    },
    timeZoneAdjusters: [],
    formatInfoCultureName: "en-US",
    formatter: SimpleFormatter,
    languagesByCode: {
        "1033": "English",
        "-1": "All Languages",
    },
};
//# sourceMappingURL=DefaultFormattingData.js.map