var LAYOUT_PROPERTY = "layout";
var FULLSCREEN_OPEN_PROPERTY = "fullscreen_open";
var FULLSCREEN_CLOSE_PROPERTY = "fullscreen_close";
var PARAMETERS = "parameters";
export { LAYOUT_PROPERTY, FULLSCREEN_OPEN_PROPERTY, FULLSCREEN_CLOSE_PROPERTY, PARAMETERS };
