//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Microsoft.CloudForFSI.Tables
{

    /// <summary>
    /// Table connecting customer insight segments to customers
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msind_industrysegment")]
    public partial class msind_industrysegment : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
    {

        /// <summary>
        /// Default Constructor.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode()]
        public msind_industrysegment() :
                base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "msind_industrysegment";

        public const string EntitySchemaName = "msind_industrysegment";

        public const string PrimaryIdAttribute = "msind_industrysegmentid";

        public const string PrimaryNameAttribute = "msind_value";

        public const string EntityLogicalCollectionName = "msind_industrysegments";

        public const string EntitySetName = "msind_industrysegments";

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;

        [System.Diagnostics.DebuggerNonUserCode()]
        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        [System.Diagnostics.DebuggerNonUserCode()]
        private void OnPropertyChanging(string propertyName)
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Contact for which measures were calculated
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msind_contactid")]
        public Microsoft.Xrm.Sdk.EntityReference msind_contactid
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msind_contactid");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.OnPropertyChanging("msind_contactid");
                this.SetAttributeValue("msind_contactid", value);
                this.OnPropertyChanged("msind_contactid");
            }
        }

        /// <summary>
        /// Customer insights internal identifier for customer (Contact or Account)
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msind_customerid")]
        public string msind_CustomerID
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<string>("msind_customerid");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.OnPropertyChanging("msind_CustomerID");
                this.SetAttributeValue("msind_customerid", value);
                this.OnPropertyChanged("msind_CustomerID");
            }
        }

        /// <summary>
        /// Unique identifier for entity instances
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msind_industrysegmentid")]
        public System.Nullable<System.Guid> msind_industrysegmentId
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("msind_industrysegmentid");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.OnPropertyChanging("msind_industrysegmentId");
                this.SetAttributeValue("msind_industrysegmentid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
                this.OnPropertyChanged("msind_industrysegmentId");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msind_industrysegmentid")]
        public override System.Guid Id
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return base.Id;
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.msind_industrysegmentId = value;
            }
        }

        /// <summary>
        /// Customer insights segment value
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msind_value")]
        public string msind_Value
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<string>("msind_value");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.OnPropertyChanging("msind_Value");
                this.SetAttributeValue("msind_value", value);
                this.OnPropertyChanged("msind_Value");
            }
        }

        /// <summary>
        /// Constructor for populating via LINQ queries given a LINQ anonymous type
        /// <param name="anonymousType">LINQ anonymous type.</param>
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode()]
        public msind_industrysegment(object anonymousType) :
                this()
        {
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();

                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int)value);
                    name = name.Remove(name.Length - "enum".Length);
                }

                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["msind_industrysegmentid"] = base.Id;
                        break;
                    case "msind_industrysegmentid":
                        var id = (System.Nullable<System.Guid>)value;
                        if (id == null)
                        { continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
        }
    }
}