import { ICustomControlHostProps, ICustomControlHostOwnProps, IClientData } from "../Models/CustomControlDataInterfaces";
import { CustomControlEntityReference } from "../Models/CustomControlEntityReference";
declare function buildUniqueCustomControlId(props: ICustomControlHostProps, id: string, absoluteId?: string): string;
declare function buildChildDomId(props: ICustomControlHostOwnProps): string;
declare function buildTesthookId(props: ICustomControlHostProps, testhookId: string): string;
declare function buildTabIndexValue(props: ICustomControlHostProps): number;
declare function buildTooltipValue(props: ICustomControlHostProps): string;
declare function getHighContrastEnabled(): boolean;
declare function focusElementById(props: ICustomControlHostProps, id: string, isAbsoluteId?: boolean): void;
declare function blurElementById(props: ICustomControlHostProps, id: string, isAbsoluteId?: boolean): void;
declare function createCrmUri(url: string, data: IClientData): string;
declare function openDatasetItemAction(ownProps: ICustomControlHostProps, param: CustomControlInterfaces.IDataSetParameter, paramKey: string, runCustomOpenRecord: any, entityReference: CustomControlEntityReference, openDataSetItemOptions?: CustomControlInterfaces.IOpenDataSetItemOptions): void;
declare function areFilteringObjEqual(firstFilteringObj: CustomControlInterfaces.FilterExpression, secondFilteringObj: CustomControlInterfaces.FilterExpression, columnAliasMap?: Record<string, any>): boolean;
declare function areSortingObjEqual(firstSortingObj: CustomControlInterfaces.IDataSetColumnSortStatus[], secondSortingObj: CustomControlInterfaces.IDataSetColumnSortStatus[]): boolean;
declare function getRecordSetQueryFromProps(ownProps: ICustomControlHostProps, paramKey: string): string;
declare function getParentIdFromProps(props: ICustomControlHostOwnProps): string;
declare function convertFetchXmlToFetchExpression(inputFetchXml: string): CustomControlInterfaces.FetchExpression;
declare function convertFetchXmlToFilterExpression(inputFetchXmlSnippet: string): CustomControlInterfaces.FilterExpression;
declare function convertFetchExpressionToFetchXml(fetchExpression: CustomControlInterfaces.FetchExpression, xmlEncode?: (s: string) => string): string;
declare function convertFilterExpressionToFetchXml(filterExpression: CustomControlInterfaces.FilterExpression, xmlEncode: (s: string) => string): string;
declare function getNodeAttributeValueFromName(inputNode: Element, attribuetName: string): string;
declare function isDataSetControl(manifest: CustomControlInterfaces.ICustomControlManifest): boolean;
declare function isQuickFormControl(configuration: CustomControlInterfaces.ICustomControlConfiguration): boolean;
declare function getRecordInfoFromControlProps(props: ICustomControlHostProps): {
    recordId: string;
    entityTypeName: string;
};
declare function getEntityTypeFromQuickFormDefaultConfiguration(configuration: CustomControlInterfaces.ICustomControlConfiguration): string;
declare function getRecordIdFromQuickFormDefaultConfiguration(configuration: CustomControlInterfaces.ICustomControlConfiguration): string;
export { buildUniqueCustomControlId, buildChildDomId, focusElementById, blurElementById, createCrmUri, openDatasetItemAction, areFilteringObjEqual, areSortingObjEqual, buildTesthookId, buildTabIndexValue, buildTooltipValue, getParentIdFromProps, getRecordSetQueryFromProps, convertFetchXmlToFetchExpression, convertFetchXmlToFilterExpression, getHighContrastEnabled, convertFetchExpressionToFetchXml, convertFilterExpressionToFetchXml, getNodeAttributeValueFromName, isDataSetControl, isQuickFormControl, getRecordInfoFromControlProps, getEntityTypeFromQuickFormDefaultConfiguration, getRecordIdFromQuickFormDefaultConfiguration, };
