import { IXrmProxy } from "../Models/CustomControlDataInterfaces";
declare class XrmProxy implements IXrmProxy {
    UserSettings: ControlAndClientApiInterfaces.UserSettings;
    OrgSettings: ControlAndClientApiInterfaces.OrgSettings;
    Utils: ControlAndClientApiInterfaces.Utils;
    Offline: ControlAndClientApiInterfaces.Offline;
    Page: ControlAndClientApiInterfaces.Page;
    Reporting: ControlAndClientApiInterfaces.Reporting;
    Diagnostics: ControlAndClientApiInterfaces.Diagnostics;
    IntelligenceApi: ControlAndClientApiInterfaces.IntelligenceApi;
    Client: ControlAndClientApiInterfaces.Client;
    GraphApi: ControlAndClientApiInterfaces.GraphApi;
    private _navigationContext;
    private _deviceContext;
    private _externalContext;
    private _applicationUI;
    private _webApiContext;
    private _unifiedWebApiContext;
    Initialized: boolean;
    constructor();
    setUserSettings(userSettings: ControlAndClientApiInterfaces.UserSettings): void;
    setOrgSettings(orgSettings: ControlAndClientApiInterfaces.OrgSettings): void;
    setOffline(offline: ControlAndClientApiInterfaces.Offline): void;
    setUtils(utilities: ControlAndClientApiInterfaces.Utils): void;
    setPage(page: ControlAndClientApiInterfaces.Page): void;
    setReporting(reporting: ControlAndClientApiInterfaces.Reporting): void;
    setIntelligenceApi(intelligenceApi: ControlAndClientApiInterfaces.IntelligenceApi): void;
    setDiagnostics(diagnostics: ControlAndClientApiInterfaces.Diagnostics): void;
    setClient(client: ControlAndClientApiInterfaces.Client): void;
    setGraphApi?(graphApi: ControlAndClientApiInterfaces.GraphApi): void;
    setNavigationContext(xrmNavigation: ControlAndClientApiInterfaces.Navigation): void;
    setDeviceContext(xrmDevice: ControlAndClientApiInterfaces.Device): void;
    setExternalContext(xrmExternalContext: ControlAndClientApiInterfaces.ExternalContext): void;
    setApplicationUI(applicationUI: ControlAndClientApiInterfaces.ApplicationUI): void;
    setWebApi(webApi: ControlAndClientApiInterfaces.WebApiSwitch): void;
    setWebApiUnified(webApi: ControlAndClientApiInterfaces.WebApi): void;
    openForm(options: ControlAndClientApiInterfaces.EntityFormOptions, parameters?: ControlAndClientApiInterfaces.Parameters, pageId?: string): Promise<ControlAndClientApiInterfaces.OpenFormSuccessResponse>;
    openUrl(url: string, options?: ControlAndClientApiInterfaces.WindowOptions, pageId?: string): void;
    openFile(file: ControlAndClientApiInterfaces.FileObject, options?: ControlAndClientApiInterfaces.OpenFileOptions, pageId?: string): Promise<void>;
    openAlertDialog(alertStrings: ControlAndClientApiInterfaces.AlertDialogStrings, options?: ControlAndClientApiInterfaces.DialogOptions, pageId?: string): Promise<ControlAndClientApiInterfaces.AlertDialogResponse>;
    openConfirmDialog(confirmStrings: ControlAndClientApiInterfaces.ConfirmDialogStrings, options?: ControlAndClientApiInterfaces.DialogOptions, pageId?: string): Promise<ControlAndClientApiInterfaces.ConfirmDialogResponse>;
    openDialog(name: string, options?: ControlAndClientApiInterfaces.DialogOptions, parameters?: ControlAndClientApiInterfaces.Parameters, pageId?: string): Promise<ControlAndClientApiInterfaces.DialogResponse>;
    openErrorDialog(options: ControlAndClientApiInterfaces.ErrorDialogOptions, pageId?: string): Promise<ControlAndClientApiInterfaces.ErrorDialogResponse>;
    openTaskFlow(name: string, options?: ControlAndClientApiInterfaces.TaskFlowOptions, parameters?: ControlAndClientApiInterfaces.Parameters, pageId?: string): Promise<ControlAndClientApiInterfaces.TaskFlowResponse>;
    openWebResource(name: string, options?: ControlAndClientApiInterfaces.WindowOptions, data?: string, pageId?: string): void;
    navigateTo(input: ControlAndClientApiInterfaces.NavigateToPageInput, options?: ControlAndClientApiInterfaces.NavigationOptions, pageId?: string): Promise<void>;
    captureImage(options?: ControlAndClientApiInterfaces.CaptureImageOptions): Promise<ControlAndClientApiInterfaces.FileObject>;
    captureAudio(options?: ControlAndClientApiInterfaces.CaptureAudioOptions): Promise<ControlAndClientApiInterfaces.FileObject>;
    captureVideo(options?: ControlAndClientApiInterfaces.CaptureVideoOptions): Promise<ControlAndClientApiInterfaces.FileObject>;
    pickFile(options?: ControlAndClientApiInterfaces.PickFileOptions): Promise<ControlAndClientApiInterfaces.FileObject[]>;
    getBarcodeValue(): Promise<string>;
    getCurrentPosition(): Promise<ControlAndClientApiInterfaces.Position>;
    getAvailableExternalContexts(): Collection.ItemCollection<ControlAndClientApiInterfaces.ExternalContextDescriptor>;
    getExternalContextProperty(externalContextId: string, externalContextPropertyId: string, options?: ControlAndClientApiInterfaces.ExternalContextPropertyOptions): Promise<ControlAndClientApiInterfaces.ExternalContextSuccessResponse>;
    invokeExternalContextAction(externalContextId: string, externalContextActionId: string, options?: ControlAndClientApiInterfaces.ExternalContextActionOptions): Promise<ControlAndClientApiInterfaces.ExternalContextSuccessResponse>;
    removeExternalContextPropertyListener(externalContextId: string, externalContextPropertyId: string, listener: ControlAndClientApiInterfaces.ExternalContextPropertyListener): void;
    addGlobalNotification(type: number, level: number, message: string, title: string, action: ControlAndClientApiInterfaces.ActionDescriptor, onCloseHandler: ControlAndClientApiInterfaces.EventHandler): Promise<string>;
    clearGlobalNotification(id: string): Promise<void>;
    clearGlobalNotifications(): Promise<void>;
    private _getWebApiContext;
    retrieveRecord(entityType: string, id: string, options?: string): Promise<WebApi.Entity>;
    createRecord(entityType: string, data: WebApi.Entity): Promise<ControlAndClientApiInterfaces.LookupValue>;
    updateRecord(entityType: string, id: string, data: WebApi.Entity): Promise<ControlAndClientApiInterfaces.LookupValue>;
    deleteRecord(entityType: string, id: string): Promise<ControlAndClientApiInterfaces.LookupValue>;
    retrieveMultipleRecords(entityType: string, options?: string, maxPageSize?: number, additionalHeadersFromCaller?: Record<string, string>): Promise<WebApi.RetrieveMultipleResponse>;
    execute(request: WebApi.ODataContract): Promise<WebApi.Response>;
    executeMultiple(requests: WebApi.ODataContract[]): Promise<WebApi.Response[]>;
    openARViewer(options: ControlAndClientApiInterfaces.ARViewerOptions): Promise<string>;
}
declare const instance: XrmProxy;
export { XrmProxy, instance };
export default instance;
