import { CultureInfo } from "../../../Utilities/CultureInfo";
import { DateFormat } from "../../CustomControlDependantInterfaces";
declare function formatPositiveDecimalValue(input: number, cultureInfo: CultureInfo, precision?: number): string;
declare function formatNegativeDecimalValue(input: number, cultureInfo: CultureInfo, precision?: number): string;
declare function getCurrencySymbol(cultureInfo: CultureInfo): string;
declare function basicFormatCurrencyValue(input: number, cultureInfo: CultureInfo, attributePrecision?: number): string;
declare function getShortDatePattern(cultureInfo: CultureInfo): string;
declare function getLongDatePattern(cultureInfo: CultureInfo): string;
declare function getShortTimePattern(cultureInfo: CultureInfo): string;
declare function getFormatPattern(cultureInfo: CultureInfo, format: DateFormat): string;
export { getFormatPattern, getCurrencySymbol, basicFormatCurrencyValue, formatNegativeDecimalValue, formatPositiveDecimalValue, getShortDatePattern, getLongDatePattern, getShortTimePattern, };
