export var OPT_OUT_CONTROLS = {
    "MscrmControls.AATabContent.AATabContent": null,
    "MscrmControls.CITabContent.CITabContent": null,
    "MscrmControls.TPTabContent.TPTabContent": null,
    "MscrmControls.WKWTabContent.WKWTabContent": null,
    "MscrmControls.OverviewTabContent.OverviewTabContent": null,
    "MscrmControls.RATabContent.RATabContent": null,
    "MscrmControls.ADCTabContent.ADCTabContent": null,
    "MscrmControls.EETabContent.EETabContent": null,
    "MscrmControls.NATabContent.NATabContent": null,
    "MscrmControls.UnifiedConfigCustomControl.UnifiedConfigCustomControl": null,
    "MscrmControls.UnifiedConfigWrapperControl.UnifiedConfigWrapperControl": null,
    "MscrmControls.PredictiveForecasting.PredictiveForecasting": null,
    "MscrmControls.AutoCaptureTabContent.AutoCaptureTabContent": null,
    "MscrmControls.Sales.Insights.LeadScoring.LeadScoringConfigControl": null,
    "MscrmControls.AcceleratedSales.SalesAccelerationSettingsControl": null,
    "SalesCadenceControls.CadenceMgmt.CadenceMgmtControl": null,
    "MscrmControls.Sales.AssistantStudioCustomControl.AssistantStudioCustomControl": null,
    "MscrmControls.Sales.AssistantStudioParentControl.TabControl": null,
    "MscrmControls.Sales.RankingTabControl.RankingTabControl": null,
    "MscrmControls.AppCommon.ContextualEmail.ContextualEmailControl": null,
};
