trigger:
  - master
  - EA
  - Features/*
  - releases/*

stages:
  - stage: Build
    pool:
      name: Azure-Pipelines-EO-Windows2019-DynamicsCRM
      demands:
        - Cmd
        - msbuild
        - visualstudio
        - DotNetFramework
    jobs:
      - job: Build
        displayName: Full Build For the Product
        timeoutInMinutes: 180

        variables:
          - group: Tools.AutoVersion

          - group: Financial_Services_Key_Vault_Secrets

          - name: SkipArtifactVersioning
            value: True

          - name: ReturnNextVersion
            value: false

          - name: UseAsPipelineBuildVersion
            value: false

          - name: BuildConfiguration
            value: release

          - name: Configuration
            value: release

          - name: BuildPlatform
            value: AnyCPU

          - name: TF_BUILD
            value: True

          - name: UsePackageVersion
            value: False

          - name: EnableLocalization
            value: True

          - name: SkipLocalizationExtraction
            value: True

        steps:
          - template: PR-build/build-template.yml
            parameters:
              pcfControls: |
                frontend\pcf-controls\**\**.pcfproj

  - stage: Deploy
    dependsOn:
      - Build
    pool:
      name: Azure-Pipelines-EO-Windows2019-DynamicsCRM
      demands:
        - Cmd
        - msbuild
        - visualstudio
        - DotNetFramework

    jobs:
      - job: Deploy
        displayName: Test Deploy of the packages
        timeoutInMinutes: 240

        variables:
          - group: Financial_Services_Key_Vault_Secrets
          - group: FSI_E2E_ENV_GROUP
          - name: BuildConfiguration
            value: release
          - name: BuildPlatform
            value: AnyCPU

        steps:
          - checkout: none
          - download: current
            artifact: FSI
          - template: PR-build/deploy-template.yml
            parameters:
              assignApiApplicationUser: true
              packages:
                - packageName: RetailBankingDataModel
                - packageName: UnifiedCustomerProfile
                  ShouldDeployCustomizationData: true
                - packageName: WealthManagement
                - packageName: LoanOnboardingCore
                  ShouldDeployCustomizationData: true
                - packageName: LoanTracker
                - packageName: FinancialServicesCommonSampleData
                  ShouldDeployCustomizationData: true
                - packageName: RetailBankingCoreSampleData
                  ShouldDeployCustomizationData: true
                - packageName: LoanOnboardingSampleData
                  ShouldDeployCustomizationData: true
                - packageName: DocumentIntelligence
                - packageName: OnboardingEssentials
                - packageName: DocumentIntelligenceSampleData
                - packageName: SampleOnboarding
                  ShouldDeployCustomizationData: true
                - packageName: SMBDataModel
                - packageName: PropertyCasualtyDataModel
                - packageName: LoanOnboardingStarter

  - stage: E2E
    dependsOn: Deploy
    pool:
      name: Azure-Pipelines-EO-Windows2019-DynamicsCRM
    jobs:
      - job: E2E_UCP
        displayName: Run UCP E2E
        timeoutInMinutes: 30

        variables:
          - group: FSI_E2E_ENV_GROUP

          - name: environmentUrl
            value: $[ stageDependencies.Deploy.Deploy.outputs['environment.environmentUrl'] ]

        steps:
          - template: e2e-template.yml
            parameters:
              env_url: $(environmentUrl)
              user: $(UCP_USER)
              user_password: $(UCP_USER_PASSWORD)
              project: "ucp-pr"

      - job: E2E_WM
        displayName: Run WM E2E
        timeoutInMinutes: 30

        variables:
          - group: FSI_E2E_ENV_GROUP

          - name: environmentUrl
            value: $[ stageDependencies.Deploy.Deploy.outputs['environment.environmentUrl'] ]

        steps:
          - template: e2e-template.yml
            parameters:
              env_url: $(environmentUrl)
              user: $(WM_USER)
              user_password: $(WM_USER_PASSWORD)
              project: "wm-pr"

      - job: E2E_LOAN
        displayName: Run Loan E2E
        timeoutInMinutes: 30

        variables:
          - group: FSI_E2E_ENV_GROUP

          - name: environmentUrl
            value: $[ stageDependencies.Deploy.Deploy.outputs['environment.environmentUrl'] ]

        steps:
          - template: e2e-template.yml
            parameters:
              env_url: $(environmentUrl)
              user: $(LOAN_USER)
              user_password: $(LOAN_USER_PASSWORD)
              project: "loan-pr"
