export const namespaces = {
    COMMON: 'common',
    GROUPS_CONTROL: 'groupsControl',
    LIFE_EVENT_BAR: 'lifeEventBar',
    CUSTOMER_SNAPSHOT_CONTROL: 'customerSnapshotControl',
    CARDS: 'cards',
    MAIN_HOUSEHOLD: 'mainHousehold',
    FINANCIAL_HOLDINGS: 'financialHoldings',
    DETAILED_FH_CONTROL: 'detailedFHControl',
    LOAN_CUSTOMER_LOOKUP: 'loanCustomerLookup',
    RELATIONSHIP: 'relationship',
    LOAN_SNAPSHOT_CONTROL: 'loanSnapshotControl',
    LOAN_APPLICATION_FILES_CONTROL: 'loanApplicationFilesControl',
    LOAN_ONBOARDING_CONTROL: 'loanOnboardingControl',
    PARTY_ASSETS_AND_LIABILITIES: 'partyAssetsAndLiabilities',
    VERIFICATION_STATUS_CONTROL: 'verificationStatusControl',
    FINANCIAL_CATEGORIES_FORM_FIELDS: 'financialCategoriesFormFields',
    INVESTMENTS_PORTFOLIOS: 'investmentsPortfolios',
    FINANCIAL_HOLDING_SELECTOR_CONTROL: 'financialHoldingSelectorControl',
};
