import { Property } from "csstype";
interface IFlexboxStyle {
    borderWidth?: number | string;
    borderBottomWidth?: number | string;
    borderLeftWidth?: number | string;
    borderRightWidth?: number | string;
    borderTopWidth?: number | string;
    height?: number | string;
    width?: number | string;
    minWidth?: number | string;
    minHeight?: number | string;
    maxWidth?: number | string;
    maxHeight?: number | string;
    margin?: number | string;
    marginBottom?: number | string;
    marginLeft?: number | string;
    marginRight?: number | string;
    marginTop?: number | string;
    padding?: number | string;
    paddingBottom?: number | string;
    paddingLeft?: number | string;
    paddingRight?: number | string;
    paddingTop?: number | string;
    position?: Property.Position;
    bottom?: number | string;
    left?: number | string;
    right?: number | string;
    top?: number | string;
}
export { IFlexboxStyle };
