export const customerFHAttributes = ['msfsi_financialholdingid', 'msfsi_customerid', 'msfsi_financialholdingrole'];

export const financialHoldingAttributes = [
    'msfsi_financialholdingid',
    'msfsi_name',
    'msfsi_description',
    'msfsi_accountingclassification',
    'msfsi_financialholdingcategory',
    'msfsi_financialholdingcode',
    'statecode',
];

export const fhAccountAttributes = [
    'msfsi_balance',
    'msfsi_balancedefault',
    'msfsi_interesttype',
    'msfsi_blockedamount',
    'msfsi_delinquencystatus',
    'msfsi_accountingclassification',
    'msfsi_financialholdingtype',
    'msfsi_numberoftransactions',
    'msfsi_unclearedbalance',
    'msfsi_interestrate',
    'msfsi_name',
    'msfsi_dateoflasttransaction',
    'msfsi_fh_accountid',
    'msfsi_averagebalance',
    'msfsi_balanceexchangerate',
    'msfsi_availablebalance',
    'msfsi_balancedefault',
    'msfsi_balance',
    'msfsi_balancedisplayvalue',
    'msfsi_balancedefaultdisplayvalue',
    'msfsi_balanceexchangerate',
    'transactioncurrencyid',
    'statecode',
];

export const fhCreditAttributes = [
    'msfsi_balance',
    'msfsi_balancedefault',
    'msfsi_monthlypaymentpercentage',
    'msfsi_delinquencystatus',
    'msfsi_nextstatementdate',
    'msfsi_laststatementdate',
    'msfsi_accountingclassification',
    'msfsi_financialholdingtype',
    'msfsi_creditlimit',
    'msfsi_lastpaymentduedate',
    'msfsi_fh_creditlineid',
    'msfsi_interestrate',
    'msfsi_name',
    'msfsi_balanceexchangerate',
    'msfsi_nextpaymentdate',
    'msfsi_minimumpaymentdue',
    'msfsi_laststatementbalance',
    'msfsi_balancedefault',
    'msfsi_balance',
    'msfsi_balancedisplayvalue',
    'msfsi_balancedefaultdisplayvalue',
    'msfsi_balanceexchangerate',
    'transactioncurrencyid',
    'statecode',
];

export const fhInvestmentAttributes = [
    'msfsi_investmentobjectives',
    'msfsi_balance',
    'msfsi_balancedefault',
    'msfsi_fh_investmentid',
    'msfsi_accountingclassification',
    'msfsi_gainloss',
    'msfsi_cashbalance',
    'msfsi_financialholdingtype',
    'msfsi_investmentrisk',
    'msfsi_name',
    'msfsi_balanceexchangerate',
    'msfsi_openeddate',
    'msfsi_performance',
    'msfsi_performance1y',
    'msfsi_performance3y',
    'msfsi_portfolioname',
    'msfsi_investmenttimeframe',
    'msfsi_performanceytd',
    'msfsi_balancedefault',
    'msfsi_balance',
    'msfsi_balancedisplayvalue',
    'msfsi_balancedefaultdisplayvalue',
    'msfsi_balanceexchangerate',
    'transactioncurrencyid',
    'statecode',
];

export const fhLoanAttributes = [
    'msfsi_balance',
    'msfsi_modeofpayment',
    'msfsi_balancedefault',
    'msfsi_collectionrisk',
    'msfsi_numberofdeferralsmade',
    'msfsi_interesttype',
    'msfsi_interestarrears',
    'msfsi_delinquencystatus',
    'msfsi_feearrears',
    'msfsi_disbursedamount',
    'msfsi_numberofinstallmentspaid',
    'msfsi_capitalarrears',
    'msfsi_principalamount',
    'msfsi_installmentamount',
    'msfsi_financialholdingtype',
    'msfsi_totalarrear',
    'msfsi_nextpaymentamount',
    'msfsi_disbursementdate',
    'msfsi_interestrate',
    'msfsi_maturitydate',
    'msfsi_name',
    'msfsi_lastpaymentdate',
    'msfsi_balanceexchangerate',
    'msfsi_fh_loanid',
    'msfsi_nextpaymentdate',
    'msfsi_accountingclassification',
    'msfsi_lastpaymentamount',
    'msfsi_repaymentaccount',
    'msfsi_dayspastdue',
    'msfsi_overduedate',
    'msfsi_totalinterestpaid',
    'msfsi_loanstartdate',
    'msfsi_nextinterestreviewdate',
    'msfsi_interestreviewperiod',
    'msfsi_balancedefault',
    'msfsi_balance',
    'msfsi_balancedisplayvalue',
    'msfsi_balancedefaultdisplayvalue',
    'msfsi_balanceexchangerate',
    'transactioncurrencyid',
    'statecode',
];

export const fhSavingAttributes = [
    'msfsi_fh_savingid',
    'msfsi_balanceexchangerate',
    'msfsi_accruedinterest',
    'msfsi_term',
    'msfsi_interestrate',
    'msfsi_balancedefault',
    'msfsi_initialsource',
    'msfsi_accountingclassification',
    'msfsi_financialholdingtype',
    'msfsi_maturitydate',
    'msfsi_projectedinterestamount',
    'msfsi_maturityinstructionsdetails',
    'msfsi_name',
    'msfsi_balanceatmaturity',
    'msfsi_balance',
    'msfsi_blockedamount',
    'msfsi_balancedefault',
    'msfsi_balance',
    'msfsi_balancedisplayvalue',
    'msfsi_balancedefaultdisplayvalue',
    'msfsi_balanceexchangerate',
    'transactioncurrencyid',
    'statecode',
];

export const fiCardAttributes = [
    'msfsi_cardtype',
    'msfsi_issuedate',
    'msfsi_cardnumber',
    'msfsi_numberofcashwithdrawal',
    'msfsi_expirydate',
    'msfsi_embossingname',
    'msfsi_dateoflasttransaction',
    'msfsi_activationdate',
    'msfsi_cardnetwork',
    'msfsi_purchasinglimit',
    'msfsi_financialinstrumenttype',
    'msfsi_dateoflastcashwithdrawal',
    'msfsi_productname',
    'msfsi_numberoftransactions',
    'msfsi_name',
    'msfsi_status',
    'msfsi_withdrawallimit',
    'msfsi_cardholder',
    'statecode',
];

export const fiDebitAttributes = [
    'msfsi_lastitemamount',
    'msfsi_lastitemstatusreason',
    'msfsi_debtoraccount',
    'msfsi_mandatelimit',
    'msfsi_financialinstrumenttype',
    'msfsi_mandatestartdate',
    'msfsi_fi_directdebitid',
    'msfsi_creditoridentifier',
    'msfsi_nextitemamount',
    'msfsi_lastitemstatus',
    'msfsi_mandateid',
    'msfsi_creditorname',
    'msfsi_name',
    'msfsi_lastitemdate',
    'msfsi_nextitemdate',
    'msfsi_mandateenddate',
    'msfsi_orderenddate',
    'msfsi_standingorderamount',
    'statecode',
];

export const fiOverdraftAttributes = [
    'msfsi_overdraftlimitused',
    'msfsi_fi_overdraftid',
    'msfsi_overdraftrate',
    'msfsi_financialinstrumenttype',
    'msfsi_overdraftlimit',
    'msfsi_name',
    'statecode',
];

export const fiStandingAttributes = [
    'msfsi_lastitemamount',
    'msfsi_lastitemdate',
    'msfsi_nextitemdate',
    'msfsi_creditoraccount',
    'msfsi_lastitemstatusreason',
    'msfsi_creditorname',
    'msfsi_lastitemstatus',
    'msfsi_nextitemamount',
    'msfsi_frequency',
    'msfsi_debtoraccount',
    'msfsi_financialinstrumenttype',
    'msfsi_firstpaymentdate',
    'msfsi_standingorderamount',
    'msfsi_fi_standingorderid',
    'msfsi_name',
    'msfsi_dayofmonth',
    'msfsi_dayofweek',
    'statecode',
];

export const financialMarketProductAttributes = ['msfsi_financialmarketproducttype', 'statecode'];

export const fhEntityToAttributes = {
    msfsi_customerfinancialholding: customerFHAttributes,
    msfsi_financialholding: financialHoldingAttributes,
    msfsi_fh_account: fhAccountAttributes,
    msfsi_fh_creditline: fhCreditAttributes,
    msfsi_fh_investment: fhInvestmentAttributes,
    msfsi_fh_loan: fhLoanAttributes,
    msfsi_fh_saving: fhSavingAttributes,
    msfsi_fi_card: fiCardAttributes,
    msfsi_fi_directdebit: fiDebitAttributes,
    msfsi_fi_overdraft: fiOverdraftAttributes,
    msfsi_fi_standingorder: fiStandingAttributes,
    msfsi_financialmarketproduct: financialMarketProductAttributes,
};
