//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CloudForFSI.UnifiedCustomerProfile.Plugins.Groups {

    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FetchXmlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FetchXmlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CloudForFSI.FSIRetailBankingCoreComponents.Plugins.Groups.FetchXmlResources", typeof(FetchXmlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch&gt;
        ///                    &lt;entity name=&apos;contact&apos;&gt;
        ///                        &lt;filter&gt;
        ///                            &lt;condition attribute=&apos;contactid&apos; operator=&apos;eq&apos; value=&apos;{0}&apos; /&gt;
        ///                        &lt;/filter&gt;
        ///                        &lt;link-entity name=&apos;msfsi_groupmember&apos; from=&apos;msfsi_member&apos; to=&apos;contactid&apos; alias =&apos;GM&apos;&gt;
        ///                            &lt;attribute name=&apos;msfsi_groupmemberid&apos; /&gt;
        ///                            &lt;filter&gt;
        ///                                &lt;condition attribute=&apos;msfsi_isgrouptypeprimar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomerPrimaryGroupFetchXmlString {
            get {
                return ResourceManager.GetString("CustomerPrimaryGroupFetchXmlString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch top=&apos;1&apos; aggregate=&apos;true&apos;&gt;
        ///                     &lt;entity name=&apos;contact&apos;&gt;
        ///                         &lt;filter&gt;
        ///                             &lt;condition attribute=&apos;contactid&apos; operator=&apos;eq&apos; value=&apos;{0}&apos; /&gt;
        ///                         &lt;/filter&gt;
        ///                         &lt;link-entity name=&apos;msfsi_groupmember&apos; from=&apos;msfsi_member&apos; to=&apos;contactid&apos; alias =&apos;GM&apos;&gt;
        ///                             &lt;link-entity name=&apos;msfsi_group&apos; from=&apos;msfsi_groupid&apos; to=&apos;msfsi_group&apos; alias=&apos;G&apos;&gt;
        ///                                 &lt;attribute  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomerTotalCountOfGroupsFetchXmlString {
            get {
                return ResourceManager.GetString("CustomerTotalCountOfGroupsFetchXmlString", resourceCulture);
            }
        }
    }
}
